jenkins:
  systemMessage: "Welcome to the Chocolatine-Powered Marvin Jenkins Instance."

  remotingSecurity:
    enabled: true

  securityRealm:
    local:
      allowsSignup: false
      users:
      - id: chocolateen
        password: ${USER_CHOCOLATEEN_PASSWORD}
        name: Hugo
      - id: vaugie_g
        password: ${USER_VAUGIE_G_PASSWORD}
        name: Garance
      - id: i_dont_know
        password: ${USER_I_DONT_KNOW_PASSWORD}
        name: Jeremy
      - id: nasso
        password: ${USER_NASSO_PASSWORD}
        name: Nassim

  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Marvin master"
            permissions:
              - "Overall/Administer"
            assignments:
              - "chocolateen"
          - name: "ape"
            description: "Pedagogical team member"
            permissions:
              - "Job/Read"
              - "Job/Build"
              - "Job/Workspace"
              - "Overall/Read"
            assignments:
              - "i_dont_know"
          - name: "gorilla"
            description: "Group Obsessively Researching Innovation Linked to Learning and Accomplishment"
            permissions:
              - "Job/Read"
              - "Job/Workspace"
              - "Job/Build"
              - "Job/Create"
              - "Job/Configure"
              - "Job/Delete"
              - "Job/Move"
              - "Job/Cancel"
              - "Overall/Read"
            assignments:
              - "vaugie_g"
          - name: "assist"
            description: "Assistant"
            permissions:
              - "Job/Read"
              - "Overall/Read"
              - "Job/Workspace"
            assignments:
              - "nasso"

jobs:
  - file: /Users/patrickeiermann/Documents/Epitech/B-DOP-400-STG-4-1-mymarvin-patrick.eiermann/job_dsl.groovy
